source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SideMenuContainer_Example', :exclusive => true do
  pod 'SideMenuContainer', :path => '../'
  pod 'iCarousel'
end

target 'SideMenuContainer_Tests', :exclusive => true do
  pod 'SideMenuContainer', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
